### ISSUE TITLE
Writen tutorial for the simple options example

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#100] opened 2020-09-15 10:27 UTC
Based on the videos, a written guide to how to start with cosmwasm-template and build your first contract from scratch.

Intro (defining task): https://vimeo.com/457486858

Setup (most is already in docs, you can add the cosmwasm-template part): https://vimeo.com/457712351

Writing contract code: https://vimeo.com/457702442

Writing tests (and json schema): https://vimeo.com/457705991

**Comment by ethanfrey** [comment] 2020-09-15 10:29
I would do this before #6 

I will do a better video for name service, once I make those names proper NFTs. That can be the second part.

@kmw101 @orkunkl you can discuss the priority of this issue relative to other tasks, but I think this is the most important tutorial/documentation task now. And a good support for the workshops.

**Comment by orkunkl** [comment] 2020-09-16 11:21
Started working on the task. I see you created a new repo for the example, @ethanfrey may I ask why created a new repo instead of putting the project into examples which is easier to discover?

**Comment by ethanfrey** [comment] 2020-09-16 12:58
I pushed it there as I made it fast using cosmwasm template. We can move it into cosmwasm examples for longer term, you are right it is better

**Comment by ethanfrey** [comment] 2020-09-16 12:58
Do you want to move it there? Then I will archive the repo with a notice it was moved

**Comment by orkunkl** [comment] 2020-09-17 13:54
Yes let's move

**Comment by ethanfrey** [comment] 2020-09-17 14:46
Please make a PR on cosmwasm-examples adding it and mention me. I will review, merge, and archive the existing repo.

**Comment by ethanfrey** [comment] 2020-09-17 14:46
Also, making a written tutorial from your subkeys workshop might be a next step after this... (thinking... new issue...)

**Comment by orkunkl** [comment] 2020-09-18 12:35
> Also, making a written tutorial from your subkeys workshop might be a next step after this... (thinking... new issue...)

I think tutorial for subkeys workshop will be kind of duplicate of simple-option workshop. 
I was considering to refactor documentation once more. We have a good and structure now.
- Let's extend advanced docs
- Fix vuepress code highlighting. It does not work now which makes harder to read code.
- Make sure documentations make sense in terms of reading order
- Add interesting and ux sugars.

**Closed as completed** 2020-09-25 07:53 UTC
